{{- if and .Values.controller.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: {{ template "jenkins.fullname" . }}
{{- if .Values.controller.prometheus.serviceMonitorNamespace }}
  namespace: {{ .Values.controller.prometheus.serviceMonitorNamespace }}
{{- else }}
  namespace: {{ template "jenkins.namespace" . }}
{{- end }}
  labels:
    "app.kubernetes.io/name": '{{ template "jenkins.name" .}}'
    {{- if .Values.renderHelmLabels }}
    "helm.sh/chart": "{{ .Chart.Name }}-{{ .Chart.Version }}"
    {{- end }}
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
    "app.kubernetes.io/component": "{{ .Values.controller.componentName }}"
    {{- range $key, $val := .Values.controller.prometheus.serviceMonitorAdditionalLabels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
{{- if .Values.controller.prometheus.serviceMonitorAdditionalAnnotations }}
  annotations:
    {{- range $key, $val := .Values.controller.prometheus.serviceMonitorAdditionalAnnotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
{{- end }}

spec:
  endpoints:
  - interval: {{ .Values.controller.prometheus.scrapeInterval }}
    port: http
    path: {{ .Values.controller.jenkinsUriPrefix }}{{ .Values.controller.prometheus.scrapeEndpoint }}
    scrapeTimeout: {{ .Values.controller.prometheus.scrapeTimeout }}
  jobLabel: {{ template "jenkins.fullname" . }}
  namespaceSelector:
    matchNames:
    - "{{ template "jenkins.namespace" $ }}"
  selector:
    matchLabels:
      "app.kubernetes.io/instance": "{{ .Release.Name }}"
      "app.kubernetes.io/component": "{{ .Values.controller.componentName }}"
{{- end }}
